torchrun --nnodes=1 \
    --nproc_per_node=4 \
    --master_port=9911 \
    lerobot/scripts/fsdp_train.py \
    --policy.type="qwen" \
    --save_freq=2000 \
    --dataset.repo_id="whatever" \
    --dataset.image_transforms.enable=true \
    --dataset.wrist_image_transforms.enable=true \
    --dataset.wrist_image_transforms.is_primary=false \
    --dataset.processor="/Data/lzl/qwen2.5_vl_7b/Qwen2.5-VL-7B-Instruct" \
    --dataset.parent_dir="/Data/lerobot_data/simulated" \
    --data_mix="simpler_fractal_sub2_plus" \
    --dataset.sample_ratio=5 \
    --output_dir="qwen_flow" \
    --batch_size=1 \
    --steps=60_0000 \
    --policy.scheduler_warmup_steps=10000 \
    --policy.scheduler_decay_steps=25000 \
    --policy.scheduler_platform_steps=20000 \
    --policy.optimizer_lr=1e-4 \
    --policy.train_main_layers=0 \
    --policy.freeze_vision_encoder=false \
    --policy.train_expert_only=false \
    --policy.train_from_scratch=true \
    --policy.pretrained_path="/Data/lzl/qwen-pi0-ft-simulated/0604-pt-85k-3-frame-libero-w-img-aug/step60000.pt" \
    --wandb.project="fsdp_qwen_pi0_ft" \
    --job_name="debug_simpler_bridge" \
    # --wandb.enable=true \
    